### ISSUE TITLE
open OutlineDropdownButton programmatically

### ISSUE THREAD

**Issue by SamadiPour** [GroovinChip/GroovinWidgets#3]
is there any way to achieve this functionality? 
i couldn't find any controller or key!

**Comment by GroovinChip** [comment]
There currently is not, but I think I can easily make that possible. I'm not able to code today, so I can't check. But I will certainly look into it. Thanks!

**Comment by SamadiPour** [comment]
@GroovinChip 
it would be nice if you do it
i'm looking forward to hear from you
thanks for your support

**Comment by GroovinChip** [comment]
@SamadiPour You are also welcome to make a PR if you need this sooner than I can make it. If you do, please make sure to write neat code and document it with the `///` notation.
